### ISSUE TITLE
Gmaps Determine Area Limitation

### ISSUE THREAD

**Issue by fauzandiMB** [fauzandiMB/Bolang-Go-NativeAndroidVersion#7]

**Comment by Budi-9** [comment]
ini maksudnya gimana?

**Comment by alvinwardh** [comment]
ini buat bikin pos nya biar ga jauh2.. tapi kita predefined kan jadinya. jadi ga jadi

**Comment by Budi-9** [comment]
engga usah mendingan, biar bebas, kan yang ngatur juga orang tua
